# CHIP.io -- hand-maintained IO pad ring (edit this file directly).
# Policy: left=IN, top/bottom/right=OUT; power pads centered on each side.
# Counts: top 27 / left 26 / bottom 24 / right 25 (incl. power).
(globals
	version = 3
	io_order = default
)
(iopad
	(topright
		(inst name="CORNERTR" )
	)
	(top
		(inst name="opad_busy" skip=15 )
		(inst name="opad_done" )
		(inst name="opad_cx_o_15" )
		(inst name="opad_cx_o_14" )
		(inst name="opad_cx_o_13" )
		(inst name="opad_cx_o_12" )
		(inst name="opad_cx_o_11" )
		(inst name="opad_cx_o_10" )
		(inst name="opad_cx_o_9" )
		(inst name="opad_cx_o_8" )
		(inst name="opad_cx_o_7" )
		(inst name="opad_cx_o_6" )
		(inst name="CORE_PG1" )
		(inst name="IO_PG1" )
		(inst name="pad_RTE" )
		(inst name="opad_cx_o_5" )
		(inst name="opad_cx_o_4" )
		(inst name="opad_cx_o_3" )
		(inst name="opad_cx_o_2" )
		(inst name="opad_cx_o_1" )
		(inst name="opad_cx_o_0" )
		(inst name="opad_cy_o_15" )
		(inst name="opad_cy_o_14" )
		(inst name="opad_cy_o_13" )
		(inst name="opad_cy_o_12" )
		(inst name="opad_cy_o_11" )
		(inst name="opad_cy_o_10" )
		(endspace gap=15 )
	)
	(topleft
		(inst name="CORNERTL" orientation=MX )
	)
	(left
		(inst name="ipad_clk" skip=15 )
		(inst name="ipad_reset" )
		(inst name="ipad_start" )
		(inst name="ipad_sel_block_i_3" )
		(inst name="ipad_sel_block_i_2" )
		(inst name="ipad_sel_block_i_1" )
		(inst name="ipad_sel_block_i_0" )
		(inst name="ipad_data_valid" )
		(inst name="ipad_data_in_15" )
		(inst name="ipad_data_in_14" )
		(inst name="ipad_data_in_13" )
		(inst name="ipad_data_in_12" )
		(inst name="CORE_PG3" )
		(inst name="IO_PG3" )
		(inst name="ipad_data_in_11" )
		(inst name="ipad_data_in_10" )
		(inst name="ipad_data_in_9" )
		(inst name="ipad_data_in_8" )
		(inst name="ipad_data_in_7" )
		(inst name="ipad_data_in_6" )
		(inst name="ipad_data_in_5" )
		(inst name="ipad_data_in_4" )
		(inst name="ipad_data_in_3" )
		(inst name="ipad_data_in_2" )
		(inst name="ipad_data_in_1" )
		(inst name="ipad_data_in_0" )
		(endspace gap=15 )
	)
	(bottomleft
		(inst name="CORNERBL" )
	)
	(bottom
		(inst name="opad_x_ready" skip=15 )
		(inst name="opad_w_o_15" )
		(inst name="opad_w_o_14" )
		(inst name="opad_w_o_13" )
		(inst name="opad_w_o_12" )
		(inst name="opad_h_o_15" )
		(inst name="opad_h_o_14" )
		(inst name="opad_h_o_13" )
		(inst name="opad_h_o_12" )
		(inst name="opad_h_o_11" )
		(inst name="opad_h_o_10" )
		(inst name="CORE_PG0" )
		(inst name="IO_PG0" )
		(inst name="POC" )
		(inst name="opad_h_o_9" )
		(inst name="opad_h_o_8" )
		(inst name="opad_h_o_7" )
		(inst name="opad_h_o_6" )
		(inst name="opad_h_o_5" )
		(inst name="opad_h_o_4" )
		(inst name="opad_h_o_3" )
		(inst name="opad_h_o_2" )
		(inst name="opad_h_o_1" )
		(inst name="opad_h_o_0" )
		(endspace gap=15 )
	)
	(bottomright
		(inst name="CORNERBR" orientation=MY )
	)
	(right
		(inst name="opad_cy_o_9" skip=15 )
		(inst name="opad_cy_o_8" )
		(inst name="opad_cy_o_7" )
		(inst name="opad_cy_o_6" )
		(inst name="opad_cy_o_5" )
		(inst name="opad_cy_o_4" )
		(inst name="opad_cy_o_3" )
		(inst name="opad_cy_o_2" )
		(inst name="opad_cy_o_1" )
		(inst name="opad_cy_o_0" )
		(inst name="opad_w_o_11" )
		(inst name="CORE_PG2" )
		(inst name="IO_PG2" )
		(inst name="IO_PG4" )
		(inst name="opad_w_o_10" )
		(inst name="opad_w_o_9" )
		(inst name="opad_w_o_8" )
		(inst name="opad_w_o_7" )
		(inst name="opad_w_o_6" )
		(inst name="opad_w_o_5" )
		(inst name="opad_w_o_4" )
		(inst name="opad_w_o_3" )
		(inst name="opad_w_o_2" )
		(inst name="opad_w_o_1" )
		(inst name="opad_w_o_0" )
		(endspace gap=15 )
	)
)
